import {
  BACKEND_URL,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID,
} from "@env";

const API_URL = BACKEND_URL || "http://127.0.0.1:8000";
export const AUTH_FIREBASE_API_KEY = FIREBASE_API_KEY;
export const AUTH_FIREBASE_AUTH_DOMAIN = FIREBASE_AUTH_DOMAIN;
export const AUTH_FIREBASE_PROJECT_ID = FIREBASE_PROJECT_ID;
export const AUTH_FIREBASE_STORAGE_BUCKET = FIREBASE_STORAGE_BUCKET;
export const AUTH_FIREBASE_MESSAGING_SENDER_ID = FIREBASE_MESSAGING_SENDER_ID;
export const AUTH_FIREBASE_APP_ID = FIREBASE_APP_ID;
export const AUTH_FIREBASE_MEASUREMENT_ID = FIREBASE_MEASUREMENT_ID;

export default {
  API_URL,
};